---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-stg
  namespace: stg
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:AP-*
spec:
  releaseName: podinfo-stg
  chart:
    git: git@github.com:stefanprodan/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: urkonn/podinfo:AP-qyhroquv
    replicaCount: 1
    hpa:
      enabled: false
